---
# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancements :zap:"
    labels:
      - "enhancement"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":wrench: Maintenance :wrench:"
    labels:
      - "chore"
      - "documentation"
      - "maintenance"
      - "dependencies"
  - title: ":mortar_board: Code Quality :mortar_board:"
    labels:
      - "code-quality"
      - "CI"
      - "test"

autolabeler:
  - label: "feature"
    title:
      - "/feat:/i"
  - label: "bug"
    title:
      - "/fix:/i"
  - label: "chore"
    title:
      - "/chore:/i"
  - label: "documentation"
    title:
      - "/docs:/i"

template: |
  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/lfreleng-actions/packer-build-action/issues)
